/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as CombinedRouteImport } from './routes/combined'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditionsIndexRouteImport } from './routes/editions.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminTelevoteRouteImport } from './routes/admin.televote'
import { Route as AdminRoundsRouteImport } from './routes/admin.rounds'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminEditionsRouteImport } from './routes/admin.editions'
import { Route as AdminDetectionRouteImport } from './routes/admin.detection'
import { Route as AdminCombinedRouteImport } from './routes/admin.combined'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAntiAbuseRouteImport } from './routes/admin.anti-abuse'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinedRoute = CombinedRouteImport.update({
  id: '/combined',
  path: '/combined',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsIndexRoute = EditionsIndexRouteImport.update({
  id: '/editions/',
  path: '/editions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelevoteRoute = AdminTelevoteRouteImport.update({
  id: '/televote',
  path: '/televote',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoundsRoute = AdminRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditionsRoute = AdminEditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDetectionRoute = AdminDetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCombinedRoute = AdminCombinedRouteImport.update({
  id: '/combined',
  path: '/combined',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAntiAbuseRoute = AdminAntiAbuseRouteImport.update({
  id: '/anti-abuse',
  path: '/anti-abuse',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/combined': typeof CombinedRoute
  '/results': typeof ResultsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/anti-abuse': typeof AdminAntiAbuseRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/combined': typeof AdminCombinedRoute
  '/admin/detection': typeof AdminDetectionRoute
  '/admin/editions': typeof AdminEditionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/rounds': typeof AdminRoundsRoute
  '/admin/televote': typeof AdminTelevoteRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/editions/': typeof EditionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/combined': typeof CombinedRoute
  '/results': typeof ResultsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/anti-abuse': typeof AdminAntiAbuseRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/combined': typeof AdminCombinedRoute
  '/admin/detection': typeof AdminDetectionRoute
  '/admin/editions': typeof AdminEditionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/rounds': typeof AdminRoundsRoute
  '/admin/televote': typeof AdminTelevoteRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin': typeof AdminIndexRoute
  '/editions': typeof EditionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/combined': typeof CombinedRoute
  '/results': typeof ResultsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/anti-abuse': typeof AdminAntiAbuseRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/combined': typeof AdminCombinedRoute
  '/admin/detection': typeof AdminDetectionRoute
  '/admin/editions': typeof AdminEditionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/rounds': typeof AdminRoundsRoute
  '/admin/televote': typeof AdminTelevoteRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/editions/': typeof EditionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/combined'
    | '/results'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/anti-abuse'
    | '/admin/audit-log'
    | '/admin/combined'
    | '/admin/detection'
    | '/admin/editions'
    | '/admin/results'
    | '/admin/rounds'
    | '/admin/televote'
    | '/admin/theme'
    | '/admin/'
    | '/editions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/combined'
    | '/results'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/anti-abuse'
    | '/admin/audit-log'
    | '/admin/combined'
    | '/admin/detection'
    | '/admin/editions'
    | '/admin/results'
    | '/admin/rounds'
    | '/admin/televote'
    | '/admin/theme'
    | '/admin'
    | '/editions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/combined'
    | '/results'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/anti-abuse'
    | '/admin/audit-log'
    | '/admin/combined'
    | '/admin/detection'
    | '/admin/editions'
    | '/admin/results'
    | '/admin/rounds'
    | '/admin/televote'
    | '/admin/theme'
    | '/admin/'
    | '/editions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CombinedRoute: typeof CombinedRoute
  ResultsRoute: typeof ResultsRoute
  EditionsIndexRoute: typeof EditionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combined': {
      id: '/combined'
      path: '/combined'
      fullPath: '/combined'
      preLoaderRoute: typeof CombinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions/': {
      id: '/editions/'
      path: '/editions'
      fullPath: '/editions/'
      preLoaderRoute: typeof EditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/televote': {
      id: '/admin/televote'
      path: '/televote'
      fullPath: '/admin/televote'
      preLoaderRoute: typeof AdminTelevoteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rounds': {
      id: '/admin/rounds'
      path: '/rounds'
      fullPath: '/admin/rounds'
      preLoaderRoute: typeof AdminRoundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editions': {
      id: '/admin/editions'
      path: '/editions'
      fullPath: '/admin/editions'
      preLoaderRoute: typeof AdminEditionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/detection': {
      id: '/admin/detection'
      path: '/detection'
      fullPath: '/admin/detection'
      preLoaderRoute: typeof AdminDetectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/combined': {
      id: '/admin/combined'
      path: '/combined'
      fullPath: '/admin/combined'
      preLoaderRoute: typeof AdminCombinedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anti-abuse': {
      id: '/admin/anti-abuse'
      path: '/anti-abuse'
      fullPath: '/admin/anti-abuse'
      preLoaderRoute: typeof AdminAntiAbuseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAntiAbuseRoute: typeof AdminAntiAbuseRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCombinedRoute: typeof AdminCombinedRoute
  AdminDetectionRoute: typeof AdminDetectionRoute
  AdminEditionsRoute: typeof AdminEditionsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminRoundsRoute: typeof AdminRoundsRoute
  AdminTelevoteRoute: typeof AdminTelevoteRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAntiAbuseRoute: AdminAntiAbuseRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCombinedRoute: AdminCombinedRoute,
  AdminDetectionRoute: AdminDetectionRoute,
  AdminEditionsRoute: AdminEditionsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminRoundsRoute: AdminRoundsRoute,
  AdminTelevoteRoute: AdminTelevoteRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CombinedRoute: CombinedRoute,
  ResultsRoute: ResultsRoute,
  EditionsIndexRoute: EditionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
